config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  scope ":variant", constraints: { variant: /hotwire|htmx|inertia|unpoly/ } do
    resources :tasks, except: :show do
      resource :completion, only: %i[create destroy], module: :tasks
    end
  end

  get "hotwire", to: redirect("/hotwire/tasks", status: 302), as: :hotwire
  get "htmx", to: redirect("/htmx/tasks", status: 302), as: :htmx
  get "inertia", to: redirect("/inertia/tasks", status: 302), as: :inertia
  get "unpoly", to: redirect("/unpoly/tasks", status: 302), as: :unpoly

  root to: "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true

  def complete!
    update!(done: true)
  end

  def uncomplete!
    update!(done: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  alias_method :raw_redirect_to, :redirect_to

  allow_browser versions: :modern
  default_form_builder ApplicationFormBuilder
  before_action :determine_variant

  inertia_share flash: -> { flash.to_hash }
  inertia_share modal: -> { @modal }

  def index
    render :index, layout: false
  end

  private

  def determine_variant
    request.variant = params[:variant].to_sym if params.key?(:variant)
  end

  def inertia_modal(modal, props:, background:)
    @modal = { component: modal, props: props }
    send(background)
  end

  def redirect_to(path, **kwargs)
    respond_to do |format|
      format.html do |variant|
        variant.htmx { htmx_redirect(path, **kwargs) }
        variant.any { super }
      end
      format.turbo_stream { turbo_redirect(path, **kwargs) }
    end
  end

  def htmx_redirect(path, **kwargs)
    assign_flashes(**kwargs)
    headers["HX-Location"] = path
    render html: "", status: :no_content
  end

  def turbo_redirect(path, **kwargs)
    assign_flashes(**kwargs)
    render turbo_stream: turbo_stream.action(:redirect, path)
  end

  def assign_flashes(**kwargs)
    kwargs.each do |(type, value)|
      flash[type] = value if self.class._flash_types.include?(type)
    end
  end
end

app/controllers/tasks/completions_controller.rb
module Tasks
  class CompletionsController < ApplicationController
    def create
      task = Task.find(params[:task_id])
      task.complete!
      redirect_to tasks_path
    end

    def destroy
      task = Task.find(params[:task_id])
      task.uncomplete!
      redirect_to tasks_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    respond_to do |format|
      format.html do |variant|
        variant.any { fresh_when @tasks }
        variant.inertia { render inertia: "tasks/index", props: { tasks: @tasks } }
      end
    end
  end

  def new
    @task = Task.new
    respond_to do |format|
      format.html do |variant|
        variant.any { fresh_when @task }
        variant.inertia { inertia_modal("tasks/new", props: { task: @task }, background: :index) }
      end
    end
  end

  def edit
    @task = Task.find(params.expect(:id))
    respond_to do |format|
      format.html do |variant|
        variant.any { fresh_when @task }
        variant.inertia { inertia_modal("tasks/edit", props: { task: @task }, background: :index) }
      end
    end
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_path, notice: "Task was successfully created.", status: :see_other
    else
      respond_to do |format|
        format.html do |variant|
          variant.any { render :new, status: :unprocessable_entity }
          variant.inertia { raw_redirect_to(new_task_url(variant: :inertia), inertia: { errors: @task.errors.full_messages }) }
        end
      end
    end
  end

  def update
    @task = Task.find(params.expect(:id))
    if @task.update(task_params)
      redirect_to tasks_path, notice: "Task was successfully updated.", status: :see_other
    else
      respond_to do |format|
        format.html do |variant|
          variant.any { render :edit, status: :unprocessable_entity }
          variant.inertia { raw_redirect_to(edit_task_url(variant: :inertia), inertia: { errors: @task.errors.full_messages }) }
        end
      end
    end
  end

  def destroy
    @task = Task.find(params.expect(:id))
    @task.destroy!
    redirect_to tasks_path, notice: "Task was successfully destroyed.", status: :see_other
  end

  private

  def task_params
    params.expect(task: [ :title, :description, :done ])
  end
end

app/helpers/application_form_builder.rb
class ApplicationFormBuilder < ActionView::Helpers::FormBuilder
  include ActionView::Helpers::TagHelper
  include ActionView::Helpers::UrlHelper

  CANCEL_CLASSES = %w[button gray]
  TEXT_FIELD_CLASSES = %w[block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full].freeze
  SUBMIT_CLASSES = %w[button green]

  def cancel(value, url = nil, options = {})
    value, url, options = "Cancel", value, url if url.nil? || url.is_a?(Hash)
    classes = options.delete(:class)
    options[:class] = class_names(CANCEL_CLASSES, classes)
    link_to(value, url, options)
  end

  def text_field(method, options = {})
    classes = options.delete(:class)
    options[:class] = class_names(TEXT_FIELD_CLASSES, classes)
    super
  end

  def submit(value = nil, options = {})
    value, options = nil, value if value.is_a?(Hash)
    classes = Array.wrap(options.delete(:class))
    options[:class] = (SUBMIT_CLASSES + classes).compact.join(" ")
    super(value, options)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hx_form_method(record)
    if record.persisted?
      :hx_patch
    else
      :hx_post
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_submit_path(task, **kwargs)
    if task.persisted?
      task_path(task, **kwargs)
    else
      tasks_path(**kwargs)
    end
  end
end

app/views/application/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotwire vs HTMX vs Unpoly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <div class="w-full">
        <div class="flex justify-center">
          <div class="w-1/2">
          <h1 class="text-3xl font-bold text-center mb-2 text-blue-500">Hotwire vs HTMX vs Unpoly</h1>
          <p class="text-center">This is a simple TODO application to compare Hotwire, HTMX and Unpoly.</p>
        </div>
      </div>
      <div>
        <p class="text-center mt-2">Click on the links below to see the selected technology in action.</p>
      </div>
      <div class="flex justify-center mt-8">
        <div class="w-1/2">
          <div class="flex justify-between space-x-4">
            <%= link_to "Hotwire", hotwire_path,
              class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded w-1/3 text-center" %>
            <%= link_to "HTMX", htmx_path,
              class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-1/3 text-center" %>
            <%= link_to "Unpoly", unpoly_path,
              class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded w-1/3 text-center" %>
          </div>
          <div class="flex justify-center space-x-4 mt-8">
            <%= link_to "Inertia.js", inertia_path,
              class: "bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded w-1/3 text-center" %>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html+hotwire.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (content_for?(:title) ? "#{content_for(:title)} // " : "") + "Hotwire" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="turbo-cache-control" content="no-cache">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags("hotwire-app") %>
  </head>

  <body data-preserve-scroll>
    <% if notice.present? %>
      <div class="flash">
        <%= notice %>
      </div>
    <% end %>

    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>

    <dialog
      class="modal"
      data-controller="modal"
      data-action="turbo:frame-load->modal#open turbo:before-render@window->modal#closeWithAnimation click->modal#backdropClose"
    >
      <%= turbo_frame_tag "modal" %>
    </dialog>
  </body>
</html>

app/views/layouts/application.html+htmx.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (content_for?(:title) ? "#{content_for(:title)} // " : "") + "HTMX" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags("htmx-app") %>
  </head>

  <body
    hx-boost="true"
    hx-ext="preload"
    hx-target="#main"
    hx-select="#main"
    hx-swap="outerHTML"
    hx-headers='{"X-CSRF-Token": "<%= form_authenticity_token %>"}'
  >
    <div id="flash" hx-swap-oob="true">
      <% if notice.present? %>
        <div class="flash">
          <%= notice %>
        </div>
      <% end %>
    </div>

    <main id="main" class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>

    <dialog
      id="modal"
      aria-modal="true"
      class="modal"
      role="dialog"
      x-data="modal"
      @click="closeIfOutside"
      @htmx:after-request="closeIfSuccessful"
      @htmx:after-swap="show"
    >
    </dialog>
  </body>
</html>

app/views/layouts/application.html+inertia.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (content_for?(:title) ? "#{content_for(:title)} // " : "") + "Inertia.js" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags("inertia-app") %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html+unpoly.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (content_for?(:title) ? "#{content_for(:title)} // " : "") + "Unpoly" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/unpoly@3.9.2/unpoly.js"></script>
    <%= javascript_importmap_tags("unpoly-app") %>
  </head>

  <body>
    <div up-flashes>
      <% if notice.present? %>
        <div class="flash">
          <%= notice %>
        </div>
      <% end %>
    </div>

    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hotwire Htmx Unpoly" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>


    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if task.errors.any? %>
  <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
    <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

    <ul>
      <% task.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_form.html+htmx.erb
<%= form_with model: task,
  data: { hx_form_method(task) => task_submit_path(task, variant: :htmx),
          hx_target: 'this',
          hx_select: 'form' },
  url: task_submit_path(task, variant: :htmx) do |form| %>

  <%= render partial: "shared/errors", locals: { task: task } %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <%= form.submit class: 'mr-2' %>
  <%= form.cancel tasks_path(variant: :htmx),
    data: { hx_push_url: true, hx_select: '#main', hx_target: '#main' },
    preload: 'mouseover' %>
<% end %>

app/views/tasks/_form.html+unpoly.erb
<%= form_with model: task,
  html: { 'up-layer': 'root' },
  url: task_submit_path(task, variant: :unpoly) do |form| %>

  <%= render partial: "shared/errors", locals: { task: task } %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <%= form.submit class: 'mr-2' %>
  <%= form.cancel tasks_path(variant: :unpoly), 'up-dismiss': 'true' %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "contents") do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tasks/edit.html+hotwire.erb
<% content_for :title, "Edit Task" %>

<div class="mx-auto md:w-2/3 w-full">
  <%= turbo_frame_tag "modal" do %>
    <h1 class="font-bold text-4xl">Editing task</h1>

    <%= render "form", task: @task %>
  <% end %>
</div>

app/views/tasks/edit.html+htmx.erb
<% content_for :title, "Edit Task" %>

<div class="mx-auto md:w-2/3 w-full">
  <div data-mode="modal">
    <h1 class="font-bold text-4xl">Editing task</h1>

    <%= render "form", task: @task %>
  </div>
</div>

app/views/tasks/edit.html+unpoly.erb
<% content_for :title, "Edit Task" %>

<div class="mx-auto md:w-2/3 w-full" up-main="root">
  <div up-main="modal">
    <h1 class="font-bold text-4xl">Editing task</h1>

    <%= render "form", task: @task %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing task</h1>

  <%= render "form", task: @task %>

  <%= link_to "Cancel", @task, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tasks/index.html+hotwire.erb
<% content_for :title, "Tasks" %>

<div class="w-full">
  <div class="mb-3 flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tasks</h1>
    <%= link_to "New task", new_task_path(variant: :hotwire),
      class: "button green",
      data: { turbo_action: "advance", turbo_frame: "modal" } %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th class="w-1/12">Status</th>
        <th class="w-4/12">Title</th>
        <th class="w-6/12">Description</th>
        <th class="w-1/12">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr id="<%= dom_id(task) %>" is="turbo-frame" data-preserve-scroll="true">
          <td class="px-6 py-4 whitespace-nowrap">
            <div class="flex items-center">
              <% if task.done? %>
                <%= link_to "✓", task_completion_path(task, variant: :hotwire),
                  class: "toggle selected",
                  data: { 'turbo-method': :delete } %>
              <% else %>
                <%= link_to " ", task_completion_path(task, variant: :hotwire),
                  class: "toggle not-selected",
                  data: { 'turbo-method': :post } %>
              <% end %>
            </div>
          </td>
          <td class="text-gray-900">
            <%= task.title %>
          </td>
          <td class="text-gray-500">
            <%= task.description %>
          </td>
          <td class="px-6 py-4 text-right">
            <%= link_to "Edit", edit_task_path(task, variant: :hotwire),
              class: "mr-3 button blue",
              data: { turbo_action: 'advance', turbo_frame: 'modal' } %>
            <%= link_to "Destroy", task_path(task, variant: :hotwire),
              class: "button red",
              data: {
                turbo_confirm: "Are you sure?",
                turbo_method: :delete
              } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/index.html+htmx.erb
<% content_for :title, "Tasks" %>

<div class="w-full">
  <div class="mb-3 flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tasks</h1>
    <%= link_to "New task", new_task_path(variant: :htmx),
      class: "button green",
      data: {
        hx_select: "[data-mode=modal]",
        hx_swap: 'innerHTML',
        hx_target: '#modal',
      },
      preload: 'mouseover' %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th class="w-1/12">Status</th>
        <th class="w-4/12">Title</th>
        <th class="w-6/12">Description</th>
        <th class="w-1/12">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr id="<%= dom_id(task) %>">
          <td>
            <div class="flex items-center">
              <% if task.done? %>
                <%= link_to "✓", task_completion_path(task, variant: :htmx),
                  class: "toggle selected",
                  data: {
                    hx_delete: task_completion_path(task, variant: :htmx),
                    hx_select: "##{dom_id(task)}",
                    hx_target: "##{dom_id(task)}",
                    hx_swap: 'outerHTML'
                  } %>
              <% else %>
                <%= link_to " ", task_completion_path(task, variant: :htmx),
                  class: "toggle not-selected",
                  data: {
                    hx_post: task_completion_path(task, variant: :htmx),
                    hx_select: "##{dom_id(task)}",
                    hx_target: "##{dom_id(task)}",
                    hx_swap: 'outerHTML'
                  } %>
              <% end %>
            </div>
          </td>
          <td class="text-gray-900">
            <%= task.title %>
          </td>
          <td class="text-gray-500">
            <%= task.description %>
          </td>
          <td class="px-6 py-4 text-right">
            <%= link_to "Edit", edit_task_path(task, variant: :htmx),
              class: "mr-3 button blue",
              data: {
                hx_select: "[data-mode=modal]",
                hx_swap: 'innerHTML',
                hx_target: '#modal',
              },
              preload: 'mouseover' %>
            <%= link_to "Destroy", task_path(task, variant: :htmx),
              class: "button red",
              data: {
                hx_confirm: "Are you sure?",
                hx_delete: task_path(task, variant: :htmx),
                hx_select: '#main',
                hx_target: '#main',
              } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/index.html+unpoly.erb
<% content_for :title, "Tasks" %>

<div class="w-full">
  <div class="mb-3 flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tasks</h1>
    <%= link_to "New task", new_task_path(variant: :unpoly),
      class: "button green",
      'up-cache': 'false',
      'up-layer': 'new modal',
      'up-main': 'modal' %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th class="w-1/12">Status</th>
        <th class="w-4/12">Title</th>
        <th class="w-6/12">Description</th>
        <th class="w-1/12">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr id="<%= dom_id(task) %>">
          <td>
            <div class="flex items-center">
              <% if task.done? %>
                <%= link_to "✓", task_completion_path(task, variant: :unpoly),
                  class: "toggle selected",
                  'up-method': :delete,
                  'up-target': "##{dom_id(task)}" %>
              <% else %>
                <%= link_to " ", task_completion_path(task, variant: :unpoly),
                  class: "toggle not-selected",
                  'up-method': :post,
                  'up-target': "##{dom_id(task)}" %>
              <% end %>
            </div>
          </td>
          <td class="text-gray-900">
            <%= task.title %>
          </td>
          <td class="text-gray-500">
            <%= task.description %>
          </td>
          <td class="px-6 py-4 text-right">
            <%= link_to "Edit", edit_task_path(task, variant: :unpoly),
              class: "mr-3 button blue",
              'up-cache': 'false',
              'up-layer': 'new modal',
              'up-main': 'modal' %>
            <%= link_to "Destroy", task_path(task, variant: :unpoly),
              class: "button red",
              'up-confirm': "Are you sure?",
              'up-method': :delete,
              'up-target': '#tasks' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.html+hotwire.erb
<% content_for :title, "New Task" %>

<div class="mx-auto md:w-2/3 w-full">
  <%= turbo_frame_tag "modal" do %>
    <h1 class="font-bold text-4xl">New task</h1>

    <%= render "form", task: @task %>
  <% end %>
</div>

app/views/tasks/new.html+htmx.erb
<% content_for :title, "New Task" %>

<div class="mx-auto md:w-2/3 w-full">
  <div data-mode="modal">
    <h1 class="font-bold text-4xl">New task</h1>

    <%= render "form", task: @task %>
  </div>
</div>

app/views/tasks/new.html+unpoly.erb
<% content_for :title, "New Task" %>

<div class="mx-auto md:w-2/3 w-full" up-main="root">
  <div up-main="modal">
    <h1 class="font-bold text-4xl">New task</h1>

    <%= render "form", task: @task %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New task</h1>

  <%= render "form", task: @task %>

  <%= link_to "Cancel", tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>